### ISSUE TITLE
failed to create projection from name: EPSG:0 from the ERDC WhiteHorse sample

### ISSUE THREAD

**Issue by spyhunter99** [ngageoint/geopackage-mapcache-android#30]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage MapCache Android Version: updated from 1.3.1 to 1.4.1
  * GeoPackage MapCache Android Source: release
  * Device or Emulator: Genton motion api23 android 6
  * Android Version Number: 
  * Google Play services Version: 
  * Android Studio Version (if applicable): 
  * Platform & OS: 
  * Other Relevant Libraries: 

#### Expected Results:

Tiles to show

#### Observed Results:

App crash due to the following output

#### Output:

08-19 20:41:37.832  6038  6038 W ProjectionFactory: Failed to create projection from name: EPSG:0
08-19 20:41:37.832  6038  6038 W ProjectionFactory: org.osgeo.proj4j.UnknownAuthorityCodeException: EPSG:0
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at org.osgeo.proj4j.CRSFactory.createFromName(CRSFactory.java:77)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at mil.nga.geopackage.projection.ProjectionFactory.fromName(ProjectionFactory.java:435)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:214)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:75)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:46)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at org.osmdroid.gpkg.GeoPackageProvider.getTileSource(GeoPackageProvider.java:120)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at org.osmdroid.samplefragments.tileproviders.GeopackageSample.addOverlays(GeopackageSample.java:157)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at org.osmdroid.samplefragments.BaseSampleFragment.onActivityCreated(BaseSampleFragment.java:83)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.os.Handler.handleCallback(Handler.java:739)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.os.Looper.loop(Looper.java:148)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at android.app.ActivityThread.main(ActivityThread.java:5417)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at java.lang.reflect.Method.invoke(Native Method)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-19 20:41:37.832  6038  6038 W ProjectionFactory:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-19 20:41:37.832  6038  6038 D AndroidRuntime: Shutting down VM
08-19 20:41:37.832  6038  6038 E UncaughtException: Got an uncaught exception: mil.nga.geopackage.GeoPackageException: Failed to create projection for authority: EPSG, code: 0, definition: null, params: null
08-19 20:41:37.832  6038  6038 W System.err: mil.nga.geopackage.GeoPackageException: Failed to create projection for authority: EPSG, code: 0, definition: null, params: null
08-19 20:41:37.832  6038  6038 W System.err:    at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:222)
08-19 20:41:37.832  6038  6038 W System.err:    at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:75)
08-19 20:41:37.833  6038  6038 W System.err:    at mil.nga.geopackage.projection.ProjectionFactory.getProjection(ProjectionFactory.java:46)
08-19 20:41:37.833  6038  6038 W System.err:    at org.osmdroid.gpkg.GeoPackageProvider.getTileSource(GeoPackageProvider.java:120)

#### Steps to Reproduce:

  1. Step One
  2. Step Two
  3. ...

#### Test Files:

The ERDC White Horse tile set

#### Additional Information:

I just updated from 1.3.1 which worked, fine, but 1.4.1 throws the mentioned error message.

**Comment by bosborn** [comment]
WhiteHorse is no longer an official sample implementation.  I still have this link to the last one I was aware of but it seems to be working.
http://portal.opengeospatial.org/files/63156

Where are you obtaining your version from?  Do you have a link?

The newest updates attempt to support different authority codes.  Code 0 should have an organization of NONE in the gpkg_spatial_ref_sys table and not EPSG.  Can you check that table on the geopackage to see what the srs_id and organization combo is?

**Comment by spyhunter99** [comment]
It is probably the same file. I also noticed it was gone from that site,
 but found a direct link on a github issue that still worked. I'll check
shortly

On Aug 21, 2017 1:23 PM, "Brian Osborn" <notifications@github.com> wrote:

WhiteHorse is no longer an official sample implementation. I still have
this link to the last one I was aware of but it seems to be working.
http://portal.opengeospatial.org/files/63156

Where are you obtaining your version from? Do you have a link?

The newest updates attempt to support different authority codes. Code 0
should have an organization of NONE in the gpkg_spatial_ref_sys table and
not EPSG. Can you check that table on the geopackage to see what the srs_id
and organization combo is?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ngageoint/geopackage-mapcache-android/issues/30#issuecomment-323803509>,
or mute the thread

**Comment by bosborn** [comment]
Closing as the WhiteHorse GeoPackage still appears to be working (organization: EPSG, coordsys id: 3857).  Let me know if you are still having issues with this.
