### ISSUE TITLE
rtree_ triggers dropped

### ISSUE THREAD

**Issue by rossia** [ngageoint/geopackage-mapcache-android#32]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage MapCache Android Version: 1.17
  * GeoPackage MapCache Android Source: (e.g. Release APK, Source Code Build) apk
  * Device or Emulator: Asus Z00VD
  * Android Version Number:  5.1
  * Google Play services Version: 11.9.75
  * Android Studio Version (if applicable): 
  * Platform & OS: 
  * Other Relevant Libraries: 

#### Expected Results:

  * What did you expect to happen?
I would expect that rtree_ triggers in the feature tables are preserved and used.

#### Observed Results:

  * What happened instead?
as the geopackage is opened, the rtree trigger in the features tables gets lost.

  * How often does this occur?
always.
#### Output:

  * Any logs, errors, or output messages?
No errors.
#### Steps to Reproduce:
1 - create a geopackage (from Qgis 2.18) with a feature (mine is named "bedding");
 2 - get sure that trigger exist to populate rtree_ tables:
select * from sqlite_master where type = 'trigger' and name = 'rtree_bedding_geom_insert':
CREATE TRIGGER "rtree_bedding_geom_insert" AFTER INSERT ON "bedding" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_bedding_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END
3 - open from MapCache the geopackage (as an external link); make no change, simply view feature contents on the map.
4 - select * from sqlite_master where type = 'trigger' and name = 'rtree_bedding_geom_insert':

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

**Comment by bosborn** [comment]
The [RTree index extension](http://www.geopackage.org/spec120/#extension_rtree) requires custom database functions which are not supported by Android (w/o using natively compiled code).  The current implementation will drop the triggers when the GeoPackage is able to be opened with write permissions.  I added an option in the [geopackage-android](https://github.com/ngageoint/geopackage-android) library to [open the GeoPackage in a readable mode](https://github.com/ngageoint/geopackage-android/commit/f8676c3bb388e80d4c5718874b8bfab038438c50) which will not drop the triggers.  When opening this way, any attempts to insert, update, or delete features will throw an exception.  This will go out in the next release this week.

**Comment by bosborn** [comment]
Changed the app to [open the GeoPackage in read only mode](https://github.com/ngageoint/geopackage-mapcache-android/commit/9b1847373abe06694d6dd72fec690d0878f24aef) whenever possible.  Upon next release, the triggers will remain as long as no feature edits are made to the GeoPackage.

**Comment by rossia** [comment]
Thanks.

**Comment by bosborn** [comment]
@rossia You can give [the new release](https://github.com/ngageoint/geopackage-mapcache-android/releases/latest) a shot, should provide you read access w/o dropping the triggers.
