### ISSUE TITLE
how to create New GeoPackage into specific folder ?

### ISSUE THREAD

**Issue by birjubhatt** [ngageoint/geopackage-mapcache-android#35]
in current situation in application when i create new GeoPackage that is default store in 
path :- /data/user/0/mil.nga.mapcache.test/databases/(createdPackageName.gpkg)

but i want to create this in my specific path like 
path :- /storage/emulated/0/MyAppName/tiles/(createdPackageName.gpkg)

how can i do this ?

**Comment by birjubhatt** [comment]
and also how to display list with this specific path ?

**Comment by bosborn** [comment]
Are you using the Google Play version, manually built, the legacy APK, or the libraries directly?

From the Google Play / master app, you can share the GeoPackage to any accepting app and move the file using any file management option.

If you are trying to share to your own app directly, you can add [intent filters](https://github.com/ngageoint/geopackage-mapcache-android/blob/664027a431b193085a50e4a873fff793e56341b9/mapcache/src/main/AndroidManifest.xml#L34) to accept shared GeoPackages and then [handle the files](https://github.com/ngageoint/geopackage-mapcache-android/blob/664027a431b193085a50e4a873fff793e56341b9/mapcache/src/main/java/mil/nga/mapcache/MainActivity.java#L143) in your main app activity to store where you'd like.

In addition to sharing, the [legacy APK](https://github.com/ngageoint/geopackage-mapcache-android/releases/download/1.24/mapcache-1.24.apk) also has an export option that saves the file to the main storage (/storage/emulated/0/).

If you are using the GeoPackage libraries ([android](https://github.com/ngageoint/geopackage-android) or [android map](https://github.com/ngageoint/geopackage-android-map)), there are many options [in the manager](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/GeoPackageManager.java) for opening external GeoPackages and listing locations.
