### ISSUE TITLE
No raster tiles drawn from the Geopackage raster file

### ISSUE THREAD

**Issue by eclectice** [ngageoint/geopackage-mapcache-android#46]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage MapCache Android Version: 2.1.0
  * GeoPackage MapCache Android Source: (e.g. Release APK, Source Code Build): Google Play Store
  * Device or Emulator: Samsung Note 5 (SM-N9208)
  * Android Version Number: 7.0
  * Google Play services Version: 21.48.13 (040400-413462841)
  * Android Studio Version (if applicable):
  * Platform & OS: Android 7.0
  * Other Relevant Libraries:

#### Expected Results:

  * What did you expect to happen?  Raster tiles from the Geopackage file are drawn in MapCache as the one shown in QGIS
 
![image](https://user-images.githubusercontent.com/1452656/147538001-4eb6df8d-83bd-49e1-8cde-c593c8376025.png)

#### Observed Results:

  * What happened instead? Tiles don't appear
![image](https://user-images.githubusercontent.com/1452656/147537900-8e3c7468-cb83-43d9-9117-eddde4fd21a2.png)

  * How often does this occur? frequently

#### Output:

  * Any logs, errors, or output messages?

#### Steps to Reproduce:

  1. Load example3.gpkg 

#### Test Files:

  * Links to any files needed for testing? 

[example3.zip](https://github.com/ngageoint/geopackage-mapcache-android/files/7783324/example3.zip)

![image](https://user-images.githubusercontent.com/1452656/147538189-47e28f01-edc6-4fc8-9713-87c9bf2dc28e.png)

![image](https://user-images.githubusercontent.com/1452656/147538246-a5f908ca-5108-41d7-912a-87988126e2b1.png)

![image](https://user-images.githubusercontent.com/1452656/147538259-5882adca-11bf-463f-9d1d-e12cb7525e50.png)

![image](https://user-images.githubusercontent.com/1452656/147538271-93117488-c26b-4684-b49a-5251ce2107e1.png)

![image](https://user-images.githubusercontent.com/1452656/147538288-23c36a76-bc2f-4f8d-a7bd-1ac43bd835b1.png)

![image](https://user-images.githubusercontent.com/1452656/147538324-bd7bca82-d26f-4f68-9ed9-f402e2b4b4e0.png)

Results of SQL queries at each zoom level:
```sql
SELECT COUNT(tile_data) from example3 where zoom_level = 0  returns COUNT(tile_data) = 0
SELECT COUNT(tile_data) from example3 where zoom_level = 1  returns COUNT(tile_data) = 0
SELECT COUNT(tile_data) from example3 where zoom_level = 2 returns COUNT(tile_data) = 0
SELECT COUNT(tile_data) from example3 where zoom_level = 3 returns COUNT(tile_data) = 0
SELECT COUNT(tile_data) from example3 where zoom_level = 4 returns COUNT(tile_data) = 0
SELECT COUNT(tile_data) from example3 where zoom_level = 5 returns COUNT(tile_data) = 272
```

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue? None

**Comment by eclectice** [comment]
Ok, even though the **example2.gpkg** only lists up to zoom level 5, but now I can see the bitmap tiles in between 16 ≤ zoom level < 18. I'm not sure what the connection is between the zoom level notion in Geopackage files and the zoom level in MapCache.

<details><summary>Screenshots between zoom level 16 and 18</summary>

Zoom level 15 (no tiles are drawn):

![image](https://user-images.githubusercontent.com/1452656/147619906-f048ef36-107f-4dc8-bd52-2860c9b1acb0.png)

Zoom level 16 (some tiles are drawn):

![image](https://user-images.githubusercontent.com/1452656/147619741-3306ab24-1dae-416e-a598-baa6b31cc0c0.png)

Zoom level 17 (some tiles are drawn):

![image](https://user-images.githubusercontent.com/1452656/147619835-87617ff2-fd60-4c47-8d6e-9daf12caf37a.png)

Zoom level 18 (no tiles are drawn):

![image](https://user-images.githubusercontent.com/1452656/147619887-c7440c72-37a6-458a-8e65-249ea17dcda1.png)


</details>

**Comment by bosborn** [comment]
You are correct that the GeoPackage zoom levels often have no relation to display zoom levels.  It is based on the tile matrix set / tile matrix bounds, matrix width/height, tile width/height, and pixel sizes.

When the map (Google) requests a XYZ tile, the bounds [are translated](https://github.com/ngageoint/geopackage-core-java/blob/5c95cf11cca8dc4783cdd3c1bc5aeaf8a5e599c2/src/main/java/mil/nga/geopackage/tiles/user/TileDaoUtils.java#L527) into a corresponding zoom level.

Using [maptiler as a reference](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/#15/-81.53/24.62) for your example location:

WGS84 datum (longitude/latitude)
-81.540527, 24.617061
-81.529541, 24.627049
Spherical Mercator (meters)
-9077050, 2828782
-9075827, 2830005
Pixels at **zoom 15**
2294272, 3601920
2294528, 3602176

(-9075827 - -9077050) / 256 = **4.77734375 pixel_x_size**
(2830005 - 2828782) / 256 = **4.77734375 pixel_y_size**

WGS84 datum (longitude/latitude)
-81.540527, 24.617061
-81.535030, 24.622051
Spherical Mercator (meters)
-9077050, 2828782
-9076438, 2829393
Pixels at **zoom 16**
4588544, 7204096
4588800, 7204352

(-9076438 - -9077050) / 256 = **2.390625 pixel_x_size**
(2829393 - 2828782) / 256 = **2.38671875 pixel_y_size**

WGS84 datum (longitude/latitude)
-81.540527, 24.622051
-81.537779, 24.624550
Spherical Mercator (meters)
-9077050, 2829393
-9076744, 2829699
Pixels at **zoom 17**
9177088, 14407936
9177344, 14408192

(-9076744 - -9077050) / 256 = **1.1953125 pixel_x_size**
(2829699- 2829393) / 256 = **1.1953125 pixel_y_size**

In your example, zoom 5 has pixel sizes of **1.78343992440569**, so tiles are returned at zoom 16 and 17.

We have a NGA (Community) [extension for tile scaling](https://ngageoint.github.io/GeoPackage/docs/extensions/tile-scaling.html) that provides tiles at zoomed in and/or out levels in NGA GeoPackage products.  You can't currently update this extension from the app, but can manually add it or do so from the l[egacy app](https://github.com/ngageoint/geopackage-mapcache-android/tree/master/docs/legacy).

Your example with updated tile scaling, zooming in an additional 2 levels for tiles:
[example3.zip](https://github.com/ngageoint/geopackage-mapcache-android/files/7802279/example3.zip)

![image](https://user-images.githubusercontent.com/11667761/147939600-0cd770b1-e8ba-4a69-b078-19d883895122.png)

![image](https://user-images.githubusercontent.com/11667761/147940781-c9e08fdc-39ac-4d68-9662-a44189b5b77d.png)

![image](https://user-images.githubusercontent.com/11667761/147941003-c4815545-e006-431c-970a-a1ef947814e7.png)

**Comment by eclectice** [comment]
I discovered this GitHub project that converts the raster map file into a Geopackage file with tile pyramids that correspond to the correct zoom levels.

https://github.com/GitHubRGI/geopackage-python
